### ISSUE TITLE
Is any_of cluster useful as a load balancer?

### ISSUE THREAD

**Issue by roeezab** [grobian/carbon-c-relay#116]
Hi,
I have the following configuration running:
_________
cluster default
    fnv1a_ch
        127.0.0.1:2003 127.0.0.1:2103 127.0.0.1:2203 127.0.0.1:2303 127.0.0.1:2403;
match * send to default;
_________

The destinations in the cluster are local carbon-cache instances, and intended for load-balancing. "Stickiness" of the same carbon-cache is not important here.

My question is - can I replace "fnv1a_ch" with "any_of", and assume that metrics will be sent evenly to the destinations? (i.e. if I have 100K metrics per minute, all carbon-cache will get ~20K metrics per minute)
I'm asking because I still want each of the carbon-cache instances to work in the same load, but I prefer to use "any_of" rather than "fnv1a_ch" algorithm, as I believe it's less consuming than "fnv1a_ch".

**Comment by grobian** [comment]
ok, so here are a few things (I use any_of for local carbon store)
- the stickyness is extremely important for the performance of the caches, so use something which tries to send the same metric to the same cache each time (this is irrelevant to your question though)
- any_of uses a fnv1a hash in the back, so essentially it uses the same balancing algorithm as fnv1a_ch, the results are different though (it's not a consistent hash)
- the big difference between any_of and fnv1a_ch is that in case a destination is unavailable, any_of will send the traffic meant for that destination to another (available) destination
- I don't think there is an essential performance difference between the two approaches, one uses slightly more work to compute the destination (fnv1a_ch) the other has a bit more complex way of delivering the results (any_of)
- last but not least, since both approaches use a hash, the balancing will be hopefully fair, but not equal, only a round-robin or so approach can do that, but that would trash your caches, see first point.  To give you an idea, I attached a graph of the distribution on one of my stores from a 30-node cluster which distributes the inbound traffic over 14 carbon-cache.py processes.
![-1](https://cloud.githubusercontent.com/assets/667105/10918613/eca21220-8266-11e5-95d7-1fac4bcbe6e0.png)

**Comment by roeezab** [comment]
Thank you very much for the detailed explanation!
So It seems I'll stick with the fnv1a_ch approach, as I have a good experience with it from the last few months.

**Comment by grobian** [comment]
The advantage of any_of in this case is that when you do a rolling restart, or any of the caches crashes/temporarily doesn't respond, the others will get the traffic, iso the traffic getting dropped at some point.

**Comment by roeezab** [comment]
I can live with some drops in case of a restart, and a case in which a specific cache crashes is very rare from my experience in the last 2-3 years. The few months I mentioned earlier is regarding my work with your (super!) relay.
But it's good to know how things work and that I have the option in case I'll need it.
Thanks again!

**Comment by grobian** [comment]
Cool! Thanks and glad I could help.
