### ISSUE TITLE
Blackhole counter is 0 when blackholing metrics

### ISSUE THREAD

**Issue by matejzero** [grobian/carbon-c-relay#134]
Hello,

I've set carbon-c-relay to blackhole around 2200 metrics, but when I check metricsBlackholed counter, it is reporting that zero metrics were blackholed. I know metrics are blackholed, because they don't hit the carbon-cache. 

Is this a bug or am I not understanding how the counter works?

My config:
```
cluster graphite_cluster
  any_of
    127.0.0.1:2103
    127.0.0.1:2203
    127.0.0.1:2303
    127.0.0.1:2403
  ;
rewrite ^servers.server_example_com\.(.*)
  into ^servers.server-old_example_com.\1
  ;
aggregate
        ^servers\.server[0-9]_example_com\.iostat\.gauge-c.t(.+)-(.+)
        ^servers\.server[0-9]_example_com\.iostat\.gauge-(data.|rpool)-(.+)
    every 10 seconds
    expire after 15 seconds
    timestamp at end of bucket
    compute sum write to
        servers.server_example_com.iostat.gauge-\1.\2
    send to graphite_cluster
    stop
    ;
match
  ^collectd.localhost
  ^servers\.server[0-9]_example_com\.iostat
  send to blackhole
  stop
  ;
match *
  send to graphite_cluster
  stop
  ;
```
Thanks...

**Comment by grobian** [comment]
This is an interesting one given what it is you're doing.

collectd.localhost entries should make blackhole increase, but
servers\.server[0-9]_example_com\.iostat will not, for it likely matches the aggregator rule, and therefore was /not/ blackholed.  In fact, you even used a stop rule here, so only metrics like servers.serverX_example_com.iostat.bla will reach the blackhole rule but I suspect you're not sending them here.

In the case where you would write this:
```
aggregate X ... ;
match X send to blackhole stop;
```
the blackhole counter will not increase, despite the aggregate not having a stop, because the metric was actually sent somewhere, e.g. it was not dropped on the floor without being seen.

Now the question is whether in your case there is input that should have been counted that isn't or not.

**Comment by matejzero** [comment]
Hey there,

thanks for answering my questions. 

To get my head straight, I did some tests:
- sending collectd.localhost metric one per second, the metricsBlackholed counter was spot on with 1 metric dropped per second
- sending collectd.localhost.test metric one per second, the metricsBlackholed counter was, again, spot on with 1 metric dropped per second. I only did this to see, if the rule is 'recursive' (will it match anything after collectd.localhost or do I  have to finish that rule with .*
So far, everything works as I thought.

I was under the impression that if I do aggregation, the source metrics get passed on, that is why I was blackholing the source metrics. But I uncommented the blackhole rule and I still didn't see 'servers.serverX_example_com.iostat.metricX' metrics. Why is that?

**Comment by grobian** [comment]
The answer is in the "stop" keyword in the aggregate rule.  Remove the blackhole rule, and remove the "stop" from the aggregate rule, and you will see the original input in graphite_cluster via the" match *" rule.

"stop" tells wether a match or aggregate falls through or not.

**Comment by matejzero** [comment]
I think my understanding of "stop" keyword was wrong.
I thought "stop" in aggregation meant: "send aggregated metric to the cluster right away instead of back to the relay, but pass through source metrics". But I guess source metrics get aggregated into a new one and source metrics dropped. Is that right?

**Comment by grobian** [comment]
Ok, I see.  "stop" here means: stop further processing of this metric.  So your latter behaviour is visible.

**Comment by matejzero** [comment]
Ok, I get it now. Thanks.

Time to write some rules...
