### ISSUE TITLE
how to replace space chars with underscores

### ISSUE THREAD

**Issue by rtoma** [grobian/carbon-c-relay#185]
Hi,

We have some collectors emitting data with space chars in the metrics name.
(Pseudo) example: ```foo bar lala <val> <timestamp>```

Carbon-c-relay seems to accept this and forwards this data to carbon-cache or go-carbon. Both do not accept metrics with spaces, complain in logs and drop them. This produces a lot of logging.

I'd like to have these metrics available (and stop the logging noise), so I am wondering how I can make carbon-c-relay replace these spaces with underscores.

Space is not in my allowed_char list.

It seems to be related to this code:
https://github.com/grobian/carbon-c-relay/blob/030c48c35e1bc22c115355260df2b9da2c029394/dispatcher.c#L441-L452

Thanks

**Comment by grobian** [comment]
Hmmm. What does a metric of `foo bar bla` mean?  carbon-c-relay simply acts innocent and treats the input up to the first space as key to route over, then forwards the input (up to \n).  Related to this is the input validation, that for performance reasons carbon-c-relay doesn't do.
I'm affraid if you say that the last two space separated units should be value and timestamp, someone else will say that the 2nd and 3rd should be because they use a fourth parameter or something.

So, carbon-c-relay could/should validate input and drop/log invalid inputs, but that wouldn't fix this issue.  Isn't it possible to fix the metric names before they arrive at the relays?

**Comment by Civil** [comment]
As far as I understand, graphite text protocol doesn't allow spaces in metric names, because space is a delimiter between name, value and timestamp, so it's much better to fix your collector, actually.

**Comment by rtoma** [comment]
Hi @grobian & @Civil  - you are right of course. Its better to fix this in the collector. Its diamond's mongo collector, so I'll push a PR there. Thanks for listening :-)
