### ISSUE TITLE
[Feature Request] detailed metrics for metricReceived

### ISSUE THREAD

**Issue by liyichao** [grobian/carbon-c-relay#190]
When we see a surge in `metricReceived`, it is hard to discover which metric is increasing.

How about adding metric for the first segment of the metric. For example:

```
test.test1
test.test2
app1.test1
```

will produce two metrics:

```
metricReceived.test
metricReceived.app1
```

So that we can see which metric category is increasing, then we can find the team who are in charge of it.

**Comment by grobian** [comment]
I think you could do this yourself:
```
aggregate ^test\.
  every X seconds
  ...
  compute count into my.prefix.metricsReceived.test
  ;
```

**Comment by liyichao** [comment]
You mean:

```
aggregate ^([^.]+)\.
  every X seconds
  ...
  compute count write to my.prefix.metricsReceived.\1
  ;
```

Is this aggregation cheap?

**Comment by grobian** [comment]
I avoided the regex, since a regex is expensive, but if you want it generic, then that's your only option.  I think you best try and see how much CPU this really costs you.  The aggregation is one of the cheapest, since it never stores any metric, and shouldn't expand into huge amount of different ones (I assume your TLD is ~20 or so).

**Comment by grobian** [comment]
I hope this was sufficient for you.  If not, please reopen.
