### ISSUE TITLE
[Feature Request] Change default connection listen backlog to 512

### ISSUE THREAD

**Issue by druchoo** [grobian/carbon-c-relay#203]
Per @redbaron in #186 512 is a reasonable default value for connection listen backlog. 

> ..setting it to 512 will do no harm whatsoever, but would make it more reliable against short burst of new incoming connections. setting it to 3 is just silly and have no reason to exist

**Comment by grobian** [comment]
http://www.linuxjournal.com/files/linuxjournal.com/linuxjournal/articles/023/2333/2333s2.html and
http://veithen.github.io/2014/01/01/how-tcp-backlog-works-in-linux.html
both seem to suggest 512 is not a good default, since 128 appears the default max for Linux. (sysctl net.core.somaxconn tells me at least).

**Comment by grobian** [comment]
So, perhaps 32 is a bit more conservative default (still much better than 5 if you need it)?

**Comment by druchoo** [comment]
I'm by no means an expert. So i'll defer to others one this. But anything higher than 5 is probably better.

**Comment by grobian** [comment]
agreed
