### ISSUE TITLE
compression between carbon-c-relays?

### ISSUE THREAD

**Issue by azhiltsov** [grobian/carbon-c-relay#212]
Hi.
I am wondering could you implement a compression between carbon-c-relays?
It is a highly compressible protocol and could give significant saving on the bandwidth.

**Comment by grobian** [comment]
Just wondering, do you actually see high bandwidth usage?  Compression complicates things a bit, an interesting test would be to run an xz tunnel (or alike) and let the relay use that tunnel.

**Comment by azhiltsov** [comment]
Yes we do. This is a traffic between relays and stores, as both of them are running carbon-c-relay it looks like an obvious solution to have a compression in between and keep a graphite compatible protocol for input and output flows
![image](https://cloud.githubusercontent.com/assets/8709761/18349653/a4e1c808-75d2-11e6-89b5-785626ebc546.png)

**Comment by dgryski** [comment]
As a comparison, enabling compression between carbonserver<->carbonzipper gave:

![network-gzip](https://cloud.githubusercontent.com/assets/970862/18351793/e706eb06-75db-11e6-8011-53c42b35ed4a.png)

**Comment by grobian** [comment]
is that context aware compression, or generic "zipping" compression?

**Comment by dgryski** [comment]
This was just gzipping the protobufs.

**Comment by grobian** [comment]
that looks promising then

**Comment by xneo64** [comment]
+1 this could save many $$ in ISP VPN bandwidth costs when transmitting data across data centres

**Comment by tehlers320** [comment]
If your multi-regional and have the budget you could have (carbon-c-relay -> telegraf -> kafka (with compression) -> telegraf elsewhere -> carbon-c-relay -> carbon-cache)

It's a bit of pipe but it does give you a big buffer for metrics that you could hang other things off of such as alarming/other graph systems. I've never seen a pipe like this in action so i'd wonder about the cpu use of telegraf/kafka.

**Comment by grobian** [comment]
My problem (design-wise) with this thing, is that I need anchorpoints both send and receive to specify the traffic is compressed or not.  Since the protocol isn't really having any wire version or something, it needs to use another port, but for that it needs configuration too.
Perhaps a separate program /is/ the easiest solution, like stunnel or something, or a different invocation of the c-relay so it can use metric-level compression or something.  It could be a memory drain, but with some communication (huffman-trees?) between relays a high compression level could be reached.  Or maybe that's too far-fetched, and is regular gzip compression already strong enough because producers typically generate trees of metrics that all share prefixes.  Meh.

**Comment by azhiltsov** [comment]
Separate invocation on the same port with enabled gzip compression should be sufficient for receiving part
For output streams this could be declared in config file on per-recipient basis.

**Comment by grobian** [comment]
This is on my todo list, it will come with a way to configure listeners instead of the current "single port is everything" approach.

**Comment by grobian** [comment]
in master there is support for sending and receiving gzipped and bzip2-ed streams.
