### ISSUE TITLE
Should fail if <port> isn't available on IPv4

### ISSUE THREAD

**Issue by beamerish** [grobian/carbon-c-relay#219]
Right now, carbon-c-relay seems to successfully start as long as its configured port is available on _any_ combination of IPv4/IPv6 and TCP/UDP on any IP. For example, it will start even its TCP port is taken on all IPv4 addresses. This makes service management quite a bit harder, since we have to use other means to determine if it's actually listening on port TCP port 2003 on IPv4, which is quite unusual.

**Comment by grobian** [comment]
I agree, and would like to go one step further than pull #220 and always require successful binding to all supported protos.  Otherwise the setup is inconsistent and unpredictible, quoting you "quite unusual".

@justincmoy: that said, care to remove the -A from your patch and unconditionally require all ports to be bound? Thanks!

**Comment by grobian** [comment]
merged and fixed
