### ISSUE TITLE
What does the metric "carbon.relays.<hostname>.destinations.internal.queued" show?

### ISSUE THREAD

**Issue by ihard** [grobian/carbon-c-relay#308]
carbon-c-relay 3.1
the metric is always 100
The other "destinations.*.queued" show the correct values.

**Comment by grobian** [comment]
It's kind of useless, it's an internal pipe that the collector (= the thing creating the self statistics) uses to send its metrics to the router, as if it were a normal client.  Because the metric is polled when the collector also produces a burst of metrics, you typically see it having stuff queued.

**Comment by ihard** [comment]
thank you!
