### ISSUE TITLE
graphite tagged metrics and match '\;'

### ISSUE THREAD

**Issue by kolobaev** [grobian/carbon-c-relay#369]
carbon-c-relay version : 3.5

Hi! I want to use separate rules for processing tagged metrics, and for this I have a separate section in the config:
```
...
match
    \;
  send to graphite
  stop
  ;
...
```
But, carbon-c-relay crashed =( :
`cat /var/log/carbon-c-relay`:
```
[2019-07-10 17:39:00] (MSG) starting carbon-c-relay v3.5 (2019-02-22), pid=25556
configuration:
    relay hostname = graphite-test
    workers = 56
    send batch size = 20000
    server queue size = 10000000
    server max stalls = 4
    listen backlog = 32
    server connection IO timeout = 5000ms
    idle connections disconnect timeout = 10m
    extra allowed characters = +/=_-:#
    configuration = /etc/carbon-c-relay.conf

[2019-07-10 17:39:00] (ERR) failed to read configuration '/etc/carbon-c-relay.conf'
```

The"; " symbol is the only indication that this metric is tagged and should be treated as something special

**Comment by grobian** [comment]
ok, when I try this:
```
testconf:5:14: syntax error, expecting 'statistics'
match \; send to foo stop;
              ^
```
What regex library did you configure with? (relay -v will show)

It's not clear to me the relay actually crashes, because it throws an error about not being able to read the configuration (it does so for me too).

So, I tried this, which works:
```
match ";" send to foo stop;
```
I just noticed that the printback doesn't quote the ; so that's obviously wrong, but it does work that way.  (You can quote expressions like that to deal with spaces and odd chars safely.)
