### ISSUE TITLE
how consistent hashing works and new graphite cluster

### ISSUE THREAD

**Issue by mmueller101** [grobian/carbon-c-relay#399]
I’m curious as to what’s the best way to switch our graphite setup while still preserving our data. We currently have four graphite machines **(A, B, C, D)**. If we created another graphite cluster with graphite machines **(E, F, G, H)**, would the consistent hashing still send those metrics all to the same graphite machine? Would all the metrics that are on machine **A** all end up on either machine **E, F, G, H**? 
We would like to create a new set of servers and during the transition process, keep all existing data without any gaps appearing in our graphs. What would happen if we added a fourth machine to the new cluster or we went down to three machines? How would this effect consistent hashing? I’ve read about carbonate, is that the best way to migrate data or is there a better way? Thanks!

**Comment by grobian** [comment]
Consider a consistent hashing cluster `foo` with nodes *A, B, C, D*.  Adding node *E* to `foo`  will result in 1/5th of each of *A, B, C, D* to be sent to the new node *E*.  Consistent here, really means that it tries to keep metrics where they are, yet respecting the balancing of the cluster.  Without consistent hashing, adding *E* to `foo` would re-assign all metrics based on the new configuration, also causing e.g. metrics from node *A* to now end up on *C*.  In the consistent case, only node *E* gets new metrics (for it is new), the previously existing nodes loose metrics.  Tools like carbonate and buffy-tools can fetch the existing metric data from *A, B, C, D* and merge/move it to *E*.

For the matter of seeing full metrics during the transition period, consider using something like carbonzipper (now in carbonapi) that will actually retrieve all copies of a metric and present the most complete (merged) version of the metric.  (Or at least that's what my first version did, and the first versions done by Damien.)

**Comment by gerases** [comment]
Thank you for your reply, but I think we're missing some basic understanding of how metric routing is done.

Let's say the old cluster consisting of _A_, _B_, _C_, _D_ is getting deprecated and on day X, we're
switching to the new cluster consisting of of _E_, _F_, _G_, _H_. The new cluster is completely empty.

What would be the steps in moving the data from the old to the new cluster with the metrics coming into the new cluster starting on day X?  If I understand, here's what the steps would be. Here, consistent hashing and a replica factor of 2 are assumed:

1. Switch the traffic to the new cluster.
2. Determine the locations in the new cluster for each of the metrics.
3. Copy the data for each metric from the old cluster to the newly assigned destinations on the new cluster.

Naturally, due to the number of the metrics, we can't do all that manually. I guess that's where the carbonate tools come in. That would mean that these tools should be able to figure out the destinations for each metric on the old and the new cluster based on the cluster configs, which would include the hashing algorithm and the replica factor? And somehow, the tools should be able to apply the consistent hashing algorithm to each metric to predict where the metrics would land on the new cluster?

Do you have an example carbonate script of how to move the data from the old cluster to the new cluster?

**Comment by grobian** [comment]
Your understanding is correct.  Obviously, you want to merge data from the old cluster into the new files on the new cluster.  This is different from copying the files over, which you could do, if you allow for some downtime.  You can tell the new cluster to get the same distribution as the old cluster, if you're happy with that distribution rate.  Else you need tools, which I don't use myself, but know exist.

**Comment by gerases** [comment]
Thank you for your response. We've been able to use various utilities from the carbonate project to do what we needed. The only remaining question I have is: where can I read about the consistent hashing algorithm used by carbon-relay. I.e., what are the inputs into it? Is it possible to predict where a metric will land given a cluster config?

**Comment by grobian** [comment]
try running relay with -t on your config (-f /path/to/conf), anything you type is taken as metric input, and it will show how/where it routes the metric

**Comment by gerases** [comment]
cool, but what goes into this decision about where to route -- especially for consistent algorithms? Obviously the metric name itself,  but what else? Are the hostnames of the carbon caches a factor as well?

**Comment by grobian** [comment]
from the readme/manpage:
```
The fnv1a_ch cluster is a identical in behaviour to carbon_ch, but it uses a different hash technique (FNV1a) which is faster but more importantly defined to get by a limitation of carbon_ch to use both host and port from the members. This is useful when multiple targets live on the same host just separated by port. The instance that original carbon uses to get around this can be set by appending it after the port, separated by an equals sign, e.g. 127.0.0.1:2006=a for instance a. When using the fnv1a_ch cluster, this instance overrides the hash key in use. This allows for many things, including masquerading old IP addresses, but mostly to make the hash key location to become agnostic of the (physical) location of that key. For example, usage like 10.0.0.1:2003=4d79d13554fa1301476c1f9fe968b0ac would allow to change port and/or ip address of the server that receives data for the instance key. Obviously, this way migration of data can be dealt with much more conveniently. The jump_fnv1a_ch cluster is also a consistent hash cluster like the previous two, but it does not take the server information into account at all. Whether this is useful to you depends on your scenario. The jump hash has a much better balancing over the servers defined in the cluster, at the expense of not being able to remove any server but the last in order. What this means is that this hash is fine to use with ever growing clusters where older nodes are also replaced at some point. If you have a cluster where removal of old nodes takes place often, the jump hash is not suitable for you. Jump hash works with servers in an ordered list without gaps. To influence the ordering, the instance given to the server will be used as sorting key. Without, the order will be as given in the file. It is a good practice to fix the order of the servers with instances such that it is explicit what the right nodes for the jump hash are.
```

**Comment by gerases** [comment]
Thanks again for the response

I went over the description several times and I don't think I quite understand the details. But I think the big picture is this. You improved the original hashing algorithm used in carbon (which was called carbon_sh). Your algorithm is called FNV1a. The old algorithm used only the hostname for calculating the hash key. Your algorithm can use both the hostname and the port. The part about `=a` and `=4d79d13554fa1301476c1f9fe968b0ac` is not clear. Do you mean that because the old algorithm uses only the host and you use both the hostname **and** the port, you can force the old behavior by appending `=a` or `=b` etc?

You also introduce another hashing algorithm named jump_fnv1a_ch. This sentence is not clear:

> The jump hash has a much better balancing over the servers defined in the cluster, at the expense of not being able to remove any server but the last in order

Specifically,  _remove any server but the last in order_. 

Does it mean the last server can be removed **or** all except the last?

Regardless of these details though, what seems to be happening is that to calculate the destination in consistent hashing, the following parameters go into the hashing function:

* Metric name
* Host name + port

Sorry for the lengthy comment!

**Comment by grobian** [comment]
While re-reading the docs, I noticed it wasn't the best piece of text. ...

Anyway, (see ch_addnode):
carbon_ch uses (host_ip + instance)
fnv1a_ch uses (host_ip + host_port) or (instance)
jump_hash uses nothing (this has to do with the order note)

The above inputs are used to calculate 100 positions per cluster server on a ring having 65535 positions.  Debug output of the relay will print all of the positions, as an FYI.

Now for each metric, to determine the matching server in the cluster, a position is calculated, see carbon_hashpos, fnv1a_hashpos and jump_bucketpos.
carbon_ch: generate MD5 of the metric, take the first two bytes as position
fnv1a_ch: calculate 32-bit FNV1a hash of the metric, fold into 16-bit as position
jump_bucketpos: do some voodoo designed by smart people

as you can see, carbon_ch uses an expensive and slow md5 hash, the fnv1a_ch takes a much faster approach.  The result, an integer between 0 and 65535, is applied to the aforementioned "ring".  The number leftmost to the position from the metric, defines the server from the cluster to route to.

For things like replication = 2, the algorithm simply searches forwards (to the right) for the first server which is different from the previously found one.

As you might see by now, the "shape" of the hash-ring, is what actually decides which metric ends up on what server.  Since carbon_ch includes host_ip, changing the ip address, causes a different ring and thus metrics ending up in different places.  With fnv1a_ch, the instance can overrule ip and port, thus you can keep the ring the same, while changing ip targets.

The jump_hash (I skipped over it mostly) is a different mammal.  It doesn't use a ring, but instead just a list with all of the servers.  The algorithm to find the appropriate server does not deal well with shrinking the list.  It only behaves nice, when removing the last server in the list.  This makes it rather unusable for scenarios where evolution of servers is to expected, e.g. replacing old ones.  Instead, this hash type achieves a near perfect distribution, unlike fnv1a_ch and carbon_ch (and in that order).

**Comment by gerases** [comment]
Thank you, this will take some time to digest, but this is _invaluable_ info that will help us be better prepared when replacing servers, changing their ips, etc. The only unclear part now is what's meant by an "instance"? Sorry if this is well known.

**Comment by grobian** [comment]
"instance" is a term from original carbon project.  In order to run multiple carbon-cache.py processes on the same host, an instance needs to be assigned.  I think this was done, because the carbon_ch ring did not include port number in its hash.  carbon-c-relay re-defined "instance" as a complete override of the hash for fnv1a, to allow for more flexible scenarios.  I tried explaining the latter above briefly.

**Comment by gerases** [comment]
Aha, got it. Now, let's say I have a four node cluster that have been assigned their places in the ring. And now suppose I want to remove member2 from the cluster and replace it with another machine (possibly another hostname and/or another ip), how do I know the ring hash of the old computer and how do I use that to assign it to the new machine? If that's described in the docs somewhere, please let me know.

**Comment by grobian** [comment]
Replacement of servers is only possible with fnv1a_ch.  The old carbon_ch can only do this if you move the IP from the old machine to the new.

```
cluster member2-replaced fnv1a_ch
  123.45.67.01:2003
  123.45.67.05:2003=123.45.67.02:2003   # 05 replaces old 02
  123.45.67.03:2003
  123.45.67.04:2003
;
```

**Comment by grobian** [comment]
You could diff the debug output with testing mode on your config to confirm the hash-ring remains the same.

**Comment by gerases** [comment]
Awesome, the ability to override the ring position is so important in my opinion. So, without any doubt, carbon c-relay comes out victorious :) Thank you for your patience with all my amateur questions.

**Comment by gerases** [comment]
I'm wondering if would make sense to write a tool that would take:

* metric name
* cluster members
* algorithm

and output which hosts would get the metric.

How difficult is it to abstract something like that out from carbon-c-relay as a standalone tool?

Carbonate's hashing doesn't match what carbon c relay does. Or so it seems.

**Comment by grobian** [comment]
testing mode of the relay (`-t`) does exactly this, doesn't it?

**Comment by gerases** [comment]
that would be impossible to use in a script and sometimes it’s very useful. i found the reason for why the results are different though. it has to do with the default value for the empty instance between python carbon and the c relay. i will fix my setup to include the instance name. maybe that’s all that is needed :)

**Comment by gerases** [comment]
@grobian, a nagging question i have is whether the "Prefix" parameter in the write_graphite plugin (https://collectd.org/wiki/index.php/Plugin:Write_Graphite) of collectd is used for any special purposes by carbon relay.

In other words, does carbon-relay treat the prepended prefix as part of the metric or does it discard it? I suspect it treats it as part of the metric name, but I just want to make sure.

**Comment by grobian** [comment]
prefix is a collectd thing that just prefixes any produced metric with the string given, e.g. so you can do servers.<dc>.<area>. as prefix (with e.g. puppet).  The graphite/carbon system never sees this separate, it just sees metrics starting with the prefix given.

**Comment by gerases** [comment]
That's what I thought as well but thank you so much for confirming!

Thank for your quick responses and expertise. This has been awesome.
