### ISSUE TITLE
Feature Request: self staticstis for memory and CPU for process/thread ? 

### ISSUE THREAD

**Issue by toni-moreno** [grobian/carbon-c-relay#45]
Hi @grobian there  is anywhere documented the carbon-c-relay daemon statistics?

I can't see metrics related to resource consumption for each process ( and thread perhaps ..) do you have plans to add them?

Lots of thanks for your great work !!!

**Comment by grobian** [comment]
What kind fo resource consumption would you want to have?  It's currently measuring time it spends, but things like cpu or memory usage are far better off measured by other tools, IMO.  Running top on a machine the relay runs on should reveal immediately if it stresses the system or not.

**Comment by toni-moreno** [comment]
I would like at least the cpu/memory as the original carbon-relay give us and metrics sent to each destination also.

![image](https://cloud.githubusercontent.com/assets/5883405/5922163/c0e0f0b0-a649-11e4-8444-3652029dcf08.png)

**Comment by AlexAkulov** [comment]
This is a good suggestion!
I also do not have enough carbon-c-relay self cpuUsage, memUsage and metricsReceived

**Comment by toni-moreno** [comment]
I have also doubts on what is the mean of each metric.

![image](https://cloud.githubusercontent.com/assets/5883405/5960474/e57885f4-a7d5-11e4-8807-d4f9a57dc6b2.png)

It seems to be like counters. ( always growing values ... ) I would like to have better  "counter_x_interval" these are  easier to draw in graphite  ( derivative() function is not needed).

**Comment by grobian** [comment]
Yes they are counters, so the use of nonNegativeDerivative is necessary if you want to see per-interval data.

**Comment by grobian** [comment]
Ok, memory usage per thread: I don't see any point in that.  There's exactly two mallocs in each worker thread, once for creating it (done during startup of the relay), and the other for creating a new connection.  This one is freed on connection close (obviously).  The rest of it is all allocated on the stack.  E.g. statistics here would be pretty flat and non-interesting.
CPU-time I can probably retrieve.  I wonder what the purpose of having it per worker is.  All workers are "non-blocking", that is, they try to do some work, and only a chunk of it.  The next worker may/will continue handling any connection.  This behaviour can be seen by looking at the idle/busy counters of the workers.  That said, the cpu usage of the full program should be indicative.

**Comment by grobian** [comment]
I'm going to close this issue since it is impossible to do this easily.  Getting memory usage is pretty much non-portable, or expensive (since the program would have to keep track of it itself).  There is IMO not much you could do with the value anyway, since the real memory consumption lives in the server queues and the aggregation buckets.  They highly repend on the pressure on the system, e.g. lots of metrics qeued (metricsQeueued) or a large amount of aggregation buckets (aggregations.metricsSent gives a good indication about that).
CPU usage should not be a concern, intra-parallelism is, which is determined by checking that stress scenarios don't yield in just one worker busy.
