### ISSUE TITLE
Feature to disable splaying of aggregation buckets

### ISSUE THREAD

**Issue by aaronm54** [grobian/carbon-c-relay#72]
My company is currently using a carbon-aggregate/cache/graphite/whisper stack, but we are trying to switch to a carbon-c-relay/cyanite/cassandra stack.  Our QA engineers are in the process of comparing the two setups.  They have some automated tools to feed data into the system and then validate it through graphite-web's render API.  The little bit of randomness that the aggregator adds when creating the aggregation buckets causes some of the tests to fail because some data points get pushed into the next bucket some of the time.

It would be great if we could disable that little bit of randomness at least in our QA environment.

**Comment by grobian** [comment]
Hmmm, I understand your case.  I don't like it in "real" settings though, for it causes avalanches, which are bad(tm).  I don't see any quick hack that could be done here, apart from modifying the code.

**Comment by tjamesturner** [comment]
i don't think the applications of this are limited to tests.  even in production, it could cause problems. for example, lets say you have a graphite query to show the ratio of the request counts between two servers to ensure the load balancer is working correctly.  if both servers report their request counts with the same timestamp, but they fall into different buckets due to splaying, then the ratio could be wildly inaccurate. similarly, we have a use case on one of our projects where we calculate the error count by subtracting the success count from the request count.  splaying would cause erroneous non-zero values in that chart followed by compensating opposite values which would greatly complicate our automated alert system.

all that said, i would still consider making a tradeoff between accuracy and performance, but i don't see the problem with avalanches. there should be several buffering queues between the carbon c relay and the carbon cache (or cyanite) both at the network layer and internally. buffer queues work quite well at leveling load. even if the carbon cache took an entire interval (or more) to process the backlog, that shouldn't cause any problems. perhaps i am missing some scenario....

**Comment by grobian** [comment]
The problem is that the expiry is done based on the boundaries, e.g. if they are all aligned, the relay has to possibly expire too many at the same time.  Perhaps this can be avoided by delaying the expiry with the splay, instead of offsetting, such that the buckets still are aligned timewise, to allow you to do the maths/deductions you mention.

**Comment by tjamesturner** [comment]
i think you could probably expire all buckets at once without issue, but if not, then perhaps it would be simpler to limit the number of simultaneous expiration based on the time left in the interval e.g. expire n buckets where n = <buckets ready to expire>*(<now> - <last bucket boundary>)/<interval>. that would ensure that all the buckets get expired by the end of the subsequent period without the overhead of tracking a separate offset for every bucket.

**Comment by grobian** [comment]
If one of you could test this to check if it works as you expect I would be grateful.

**Comment by tjamesturner** [comment]
preliminary testing seems to indicate this is working as i would expect.  i will do more thorough testing and let you know if i see any issues.

as a side note, i have modified my code locally with the fix i proposed for issue #35

**Comment by grobian** [comment]
yeah, that's ok, I still need to find some time to implement that one
