### ISSUE TITLE
[idea] implement compressed transport

### ISSUE THREAD

**Issue by grobian** [grobian/carbon-c-relay#75]
Completely backwards incompatible, but could be used between two c-relays to speed up transfers inbetween over slow lines or when using extreme/insane amounts of metrics.  Compression algorithm could be something extremely light like LZA or even worse, or turbo-charged compressor like XZ.

**Comment by chjohnst** [comment]
+1

This would be awesome!

**Comment by filippog** [comment]
sounds like a good idea! on the receiving side to keep a bit of backwards compatibility I guess the stream could be sniffed for plaintext vs compression when a client first connects (I'm assuming this would be over tcp only?)

**Comment by grobian** [comment]
If you build really nice blocks (and your compression technique is block-based), you could fit in an UDP package in theory.

Devil would be in the details to reliably make the difference between compression and non-compression.

Heck, when one would do this, SSL would also be an option to satisfy those who seek full SSL/encryption everywhere.

I'd use separate ports/listeners for this so it's easier to implement and abstract away internally.

**Comment by Civil** [comment]
I'd say that it's better to use binary protocol (rearranged of course), it'll also save some time in converting data from text to binary and vice versa.

About compression, AFAIR one of the most efficient stream-compression algorithms (CPU efficient of course) is LZ4. But the best way to compress the data is to have some sort of dictionary (especially for names), like SDCH for HTTP - if you'll pass dictionary at first, and after that only hashes of items, instead of text (I'm talking only about names) it'll be much more efficient (both CPU and ratio) than any standard algorithm. But that'll require much more work/support for that.

**Comment by grobian** [comment]
Since carbon-c-relay is in C, and it deals with the string <metric> <value> <timestamp> anyway, I don't think binary protocols will speed things up, rather complicate (the relay doesn't parse <value> or <timestamp> unless it has to).
Using dictionaries or huffman encodings require to negotiate, which looses the stateless property of the relays at the moment. Simple block-based compression techniques allow to re-send stuff and stay without state.

**Comment by Civil** [comment]
Binary protocol will speedup things if carbon-c-relay will receive already binary data. Also it'll save some bandwidth, cause for float numbers you've got fixed 64 bit size, and for strings it can be a bit more than that. For timestamp 32bits vs. 80 bits for string representation. It's also may be a good idea convert strings to float as early as possible, but that depends on how much space CPU you have on that relay. Ideally, sender should send already binary data.

About dictionaries - yeah, relay will be stateful. But that can save really a lot of network traffic, more than any block-based compression you'll use.

**Comment by grobian** [comment]
The binary representation of a string, is ... a string, that's around 95% of the data transferred, hence binary protocol doesn't change much.  The remaining 5% is only parsed when necessary (aggregations), so in the majority of cases, you're dealing with 100% strings.

**Comment by grobian** [comment]
Unlikely I'll find a reason soon to do anything on this topic.  Closing for now.

**Comment by pkittenis** [comment]
Hi @grobian, I'm interested in tackling this, perhaps you have some pointers on best place to put inflation/deflation? 

Looks like dispatcher works on individual metrics which it adds to server queue and if deflation were added there, it would be on a per metric basis and inefficient. Is this correct, if so where should inflation go?

**Comment by grobian** [comment]
hi @pkittenis what is the best place highly depends on your use-case. 

The only thing I can think of right now is transport inbetween two relays, which one could accomplish using simple compression tunnels (nc -k -l -p 6003 | xz -d | nc localhost 2003) as well.

**Comment by pkittenis** [comment]
Yes, the use case is compression of traffic between carbon-c-relays (only).

Tunnels would work but can get complicated very quickly if wanting to run in proxy mode, ie leave netcat running and compress a stream passing through. Compression utilities only close the compressed stream at end of input stream, which with netcat only happens when the connection is closed.

A dedicated tcp proxy would do it but could be avoided if it's easier to do in relay.

**Comment by grobian** [comment]
To do the transport you need two components, a server target and a receptor.  The first would be sort of easily doable, the second requires additional listener code that distinguishes from regular in what it proxies internally to a normal connection, or when the connection can be identified, an override to the read call, to wrap the unpack in there.

Why would you need the compression utility to close the compressed stream?  Can't you compress over the full stream instead?

**Comment by pkittenis** [comment]
No, what I mean is:

Sender: `nc -l -p 6000 | gzip -cf | nc localhost 2003`
Receiver: `nc -l 2003 | gunzip -cf | nc localhost 2013` where 2013 is target relay listen port.

This works fine but nc only listens for one connection. Changing it to use `-k` makes the pipe into gzip/gunzip to not terminate, at least that's what my understanding of it is, and gzip never closes the compressed stream when the connection ends. It might be that my understanding is incorrect however?

**Comment by grobian** [comment]
I think you're right, but why is it a problem?  does it buffer things because of that?  My knowledge of compression algorithms is rusty here, but a stream-compatible algorithm (block-based?) should be chosen here.  You don't want to re-negotiate for each and every metric you want to write.

**Comment by pkittenis** [comment]
It's a problem because the receiver will not pipe output from gunzip to target relay until the compressed stream is closed, I believe, which with `-k` never happens. So the target relay gets no input :) Tried without pipe buffer too, same result. If you try the above commands and make `2013` be another `nc -lk 2013`, it will receive no input if `-k` is used.

With (compressed) ssh port forward otoh, it works fine.

**Comment by grobian** [comment]
gzip uses buffering and waits for its buffer to run full, or end of stream to be reached.  The current implementation in the relay decompresses input ASAP, and does not show these delays.
