### ISSUE TITLE
any way to force statistics destination to local carbon  ?

### ISSUE THREAD

**Issue by toni-moreno** [grobian/carbon-c-relay#76]
There is any way to say carbon-c-relay to send statistics over a local carbon ? 

after install this is my process name 
```
/usr/bin/carbon-c-relay -p 2003 -w 16 -b 2500 -q 100000 -H locahost01 -f /opt/carbon-c-relay/etc/carbon-c-relay.conf
```
but sending to 

```
root: > grep -Ev "^ *#|^ *$" "/opt/carbon-c-relay/etc/carbon-c-relay.conf"
cluster local_carbon
  forward
    127.0.0.1:2013
  ;
cluster remotehost
  forward
    remotehost01:2013
  ;
match *
  send to remotehost
  stop
  ;
```

**Comment by toni-moreno** [comment]
I've added this match and seems to work ok , but could be better perhaps to add a  new parameter  -h "localhost:2013"  (by example)

```
match carbon.relays.*
    send to local_carbon
    stop
    ;
```

**Comment by grobian** [comment]
Your match is the way to do it.  The relay doesn't know what is what (that there may be a thing like local and remote) ... you need to tell it where to route what traffic :)
In your case (since you used -H) you can even restrict the match to `^carbon\.relays\.locahost01\.`. (note the escaping and leading ^, they make matching significantly faster)
