### ISSUE TITLE
Collector (carbon.*) metrics are cumulative

### ISSUE THREAD

**Issue by withnale** [grobian/carbon-c-relay#80]
Right now the metrics generated by the collector, such as carbon.relays.myrelay.metricsReceived are cumulative, which makes it difficult to generate a graph to detect abnormalities in the graphite infrastructure.

The equivalently named metrics in the graphite-project carbon daemons resets every metric interval. Is it possible to adopt this behaviour?

**Comment by grobian** [comment]
not at the moment, in a separate branch, I was/am working on abilities to perform the equivalent of the derivative() function inside the relay, which would in fact solve this problem

**Comment by withnale** [comment]
Can you share the branch? I can have a look, or a bit of a hack

**Comment by grobian** [comment]
https://github.com/grobian/carbon-c-relay/tree/issue-61-aggregation-full-bucket-calculation

**Comment by withnale** [comment]
I'm confused. The scope of this change is much broader than I would have thought would be required to make the carbon.relay.* metrics comparable to graphite project ones.

I would have thought most of the changes would be to have collector.c keep track of the previous value of each accumulating metric and just subtract that off during each METRIC_INTERVAL period.

**Comment by withnale** [comment]
Since the server_get_metrics (and other functions) seem to only be used by the collector, isn't it valid to just reset the counter after reading it?

I've done this in PR #89

**Comment by grobian** [comment]
Yes, but that is a backwards incompatible change, and thus breaks existing behaviour in a way which is not ok.

**Comment by withnale** [comment]
True, but to be honest, I thought the existing functionality was a bug. I'm not sure how you can use the existing metrics to detect abnormalities when they are contstantly increasing (without applying numerous graphite functions). Is there a graph you can share (or graphite target= function) that shows how you use it in the current state?

Regarding the PR - I'm happy to enhance the PR to make the changes dependent on a command line switch.

**Comment by grobian** [comment]
I use nonNegativeDerivative everywhere
![schermafbeelding 2015-07-31 om 14 35 54](https://cloud.githubusercontent.com/assets/667105/9007442/8a3017f6-3791-11e5-94b3-d72b0a25d8cf.png)

**Comment by sbengo** [comment]
Hi, sorry for reuse this issue, but actually its related.

Following your advices and assuming that all metrics generated are cumulative, @toni-moreno and me had been using the nonNegativeDerivative function to plot the metrics.

The problem is, when we were redoing a graph with the metric `*.destinations.*.queued` we obtained the next graph (generated by Grafana)

![image](https://cloud.githubusercontent.com/assets/13196237/10538820/7f313d20-73fb-11e5-899a-d2dc0f352266.png)

As I can see, it seems that there is not cumulative behavior on this metric, so I don't know if use or not the nonNegativeDerivate funcion to plot it. Can you please check it?

Thanks for all!

**Comment by grobian** [comment]
Yeah, queued can't be a cumulative behaviour, for it is a measurement on the current size of the queue.  This one goes up and down, and is just an approximation of queue pressure.

**Comment by sbengo** [comment]
Great! Thanks @grobian!
