### ISSUE TITLE
Metric hashing inconsistencies

### ISSUE THREAD

**Issue by jjneely** [grobian/carbon-c-relay#84]
Greetings,

I recently implemented carbon's hashing routine in Go for a tool I wrote to help manage large consistent hashing clusters.  One quirk I ran into is this:

https://github.com/jjneely/buckytools/commit/74b1ca565a0384345c7ee19055d048a5edb8014e

Python's bisect.insort() method compares each tuple to each other rather than just the ring position which changes the order of the built hashring in some collision cases.  I don't see that this code handles this case.

Have folks noticed small differences where metrics are routed as compared to Graphite's carbon implementation?

**Comment by grobian** [comment]
Thanks for letting me know!

For "us", we moved away from carbon_ch quickly as we build out new clusters to increase their size (for that's simply less work), so didn't notice any.  There is also a TODO (https://github.com/grobian/carbon-c-relay/blob/master/consistent-hash.c#L138) in the code for a collision which upstream solved, but I didn't want to fix it not to change the order.

I've looked at your commit.  I can implement the same, however it will affect the fnv1a_ch too.  Now I'm thinking about it more, the problem is worse, since qsort() isn't stable, so the results are really undefined here.  Collisions are bad in the first place, if they occur, the cluster sizes are probably getting to big with the default hash_replicas of 100.

Currently the order can change in carbon-c-relay if you change the order in which the servers are added.  The effect is minimal, if not absent, on cluster sizes <= 15 as I tested this by accident in production.  That said, I can probably make the hash more stable by using a similar comparator as the one you implemented.
Perhaps I implement something to compare the hash pos list and see if it would give a change in our setup before changing it.

**Comment by grobian** [comment]
I see you already spotted the same commit as I did (TODO), so you can ignore that one ;)

**Comment by jjneely** [comment]
Heh...I figured it would affect fnv1a_ch as well with your implementation which is why I wanted to ask if you've seen similar.  Is that what you use for larger clusters?

I was actually looking to see if there was an easy way to get your code to dump out the hash ring it generated so that I could compare.  That's been how I've tuned my Go implementation to match Carbon's.

**Comment by grobian** [comment]
Our clusters are currently 10-20 nodes, and all of them indeed use fnv1a_ch to offload cpu on the relays and get slightly better balancing.

I'm going to write the stuff to dump out the hash ring, to be able to compare and see the effect of changes.  So we could use that to compare to the Go implementation as well.

**Comment by jjneely** [comment]
See PR #85

**Comment by grobian** [comment]
Ok, for our entire config, no changes to the hash-ring occur with these changes

**Comment by grobian** [comment]
So, now coming back to the TODO (https://github.com/graphite-project/carbon/commit/024f9e67ca47619438951c59154c0dec0b0518c7) it seems like that is a very bad commit, for it will introduce unstable output if the input list is changed in order.
It does mean, however, that no collissions occur, hence the entire entrycmp code can go back to how it was, since all positions will be unique.
Implementing that change will not make a difference for our setup, since no collissions exist currently.

**Comment by grobian** [comment]
Since implementing the unique positions in carbon-c-relay is harder, I'm going to discard it since its effect will be minimal, if ever to be observed.
