### ISSUE TITLE
Can the relay refuse connections if the queue is full?

### ISSUE THREAD

**Issue by mwmanley** [grobian/carbon-c-relay#90]
Greetings,

I had an issue this week where my relays' queues will filled due to an upstream problem on my graphite servers' backends.  Since my relays handle 4.8M requests a minute, when the upstreams fill, it means a massive loss of metrics.

All my feeding servers send data to their local relays, which in turn send their data into the relays of my graphite servers.  It is possible a la sendmail to have relays refuse connections when their respective queues are filled rather than drop metrics, which is what seems to be happening?  This way, they could have all buffered on their local relays and retransmitted them all once the graphite servers became available again.

Thanks!

**Comment by grobian** [comment]
Perhaps that can be implemented as optional feature.  It currently – on purpose – behaves exactly as you laid out not to disrupt the entire service when an upstream target goes down.

**Comment by mwmanley** [comment]
That would be awesome.  Thanks!

**Comment by grobian** [comment]
I sort of understand what you're talking about.  We do 21M/min and if a store goes down, we cannot afford the relay blocking.

Question for you on behaviour here:
When exactly should the relay block you? What kind of clusters do you use?  I'm asking, because in the scenario of a non any-of cluster, where one of the stores is down, should it block even though all but just one target is down?  It will make the relay in certain scenarios block everything pretty much as soon as one store becomes unreachable.

**Comment by mwmanley** [comment]
The clients use any_of to feed a various number of graphite servers, which just forward to their local daemons (I'm running a fork of cyanite).  If that fails for some reason, and the queue backlogs, it would be nice if the cyanite feeding relay could stop accepting new data when it's full so that the local client relays can queue their data, then transmit when the cyanite relays are available again. 

I know this sounds potentially weird, and it's hard to really explain.

**Comment by grobian** [comment]
this is probably the inverse of issue #172, you could use `-L 15`, but that only gives you 15 seconds, so you could alter the code to allow longer stalling, if you need to.

**Comment by mwmanley** [comment]
Thank you, I will try it!

**Comment by redbaron** [comment]
that '-L' logic is really weird and plain wrong - partial writes are no way indication of error or problem by any means. TCP has a perfect mechanism to apply backpresure - receive windows and congestion control, if you want to slowdown ingestion just stop reading from incoming sockets and everything will slowdown naturally.

Correct logic would be (I assume that there are server submittings threads which are fetching units of work from a queue which is itself populated by metrics receiving threads):

1) write to server, anything unwritten is left in buffer, don't fetch from queue until buffer is empty (or above some low watermark)
2) queue starts to grow
3) once it reaches its max size, submitting threads will not be able to submit to queue. then they can either:
  - block on submission (which will naturally prevent them from reading from incoming sockets)
  - set a timer to check queue again, exclude socket it read last from being read until queue is free again and move on serving other incoming sockets. This will make it last a bit longer, but in case of `_ch` routing strategies all incoming socket will eventually try to write to a blocked queue anyway, so it might be not worth the effort.
4) sockets which submitting threads are  serving will accumulate data in kernel buffers, because userland doesn't read anything from them (default values controlled via `net.ipv4.tcp_rmem` sysctl, non-default values can be set with appropriate `setsockopt` calls)
5) kernel will shrink receive window and send it back to senders making them stop/slowdown transmission

Once problems goes away, everything just naturally resumes , no metrics lost (assuming clients are not timed out, but you can do nothing about that, since you can't keep buffering metrics forever).

**Comment by grobian** [comment]
Hi, this is actually exactly what's implemented.  Thanks.  -L is what you call the timer.
