### ISSUE TITLE
Give threads a name to allow pinpointing chokepoints

### ISSUE THREAD

**Issue by rtoma** [grobian/carbon-c-relay#97]
With ```top -p <pid> -H``` one can see all threads of a process.

Example output for me:
```
top - 21:33:44 up 54 days,  4:43,  1 user,  load average: 1.46, 1.33, 1.19
Tasks:  20 total,   0 running,  20 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.9%us,  0.7%sy,  0.0%ni, 98.4%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  132119240k total, 128266424k used,  3852816k free,  1389176k buffers
Swap: 16777212k total,    33692k used, 16743520k free, 119320964k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
28123 carbon-c  20   0  546m  26m  988 S  0.7  0.0   0:01.82 carbon-c-relay
28109 carbon-c  20   0  546m  26m  988 S  0.3  0.0   0:00.51 carbon-c-relay
28110 carbon-c  20   0  546m  26m  988 S  0.3  0.0   0:00.51 carbon-c-relay
28113 carbon-c  20   0  546m  26m  988 S  0.3  0.0   0:00.45 carbon-c-relay
28117 carbon-c  20   0  546m  26m  988 S  0.3  0.0   0:00.46 carbon-c-relay
28120 carbon-c  20   0  546m  26m  988 S  0.3  0.0   0:00.48 carbon-c-relay
28122 carbon-c  20   0  546m  26m  988 S  0.3  0.0   0:01.79 carbon-c-relay
28108 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.08 carbon-c-relay
28111 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.54 carbon-c-relay
28112 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.52 carbon-c-relay
28114 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.43 carbon-c-relay
28115 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.42 carbon-c-relay
28116 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.43 carbon-c-relay
28118 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.45 carbon-c-relay
28119 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.46 carbon-c-relay
28121 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.40 carbon-c-relay
28124 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:01.99 carbon-c-relay
28125 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:01.97 carbon-c-relay
28126 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.22 carbon-c-relay
28127 carbon-c  20   0  546m  26m  988 S  0.0  0.0   0:00.08 carbon-c-relay
```

Wouldn't it be cool to name the threads with their task (collector, dispatcher, ...) so you can see which are busiest and maybe causing trouble?

Best I could find for C is how redis does it: http://download.redis.io/redis-stable/src/setproctitle.c

**Comment by grobian** [comment]
Modifying argv[0] is modifying the process name, threads are "light weight processes", that is, they share the context of the same process, therefore, that trick wouldn't work.  I don't think it is possible at all due to the nature of threads.  As you can see in top's output, the only difference between the threads is their CPU usage, the rest is all the same (= the process).  carbon-c-relay keeps metrics for all its dispatchers, which should help you to find out if they are over-stressed or not.

If you have a real resource problem, I'm more than happy to look into how to reveal what is busy the most.  Yet, I haven't been able to get the relay use more than 4 cores at the same time on our busiest servers, so never bothered myself to look at what's taking the most time (on a 24-core machine).

**Comment by rtoma** [comment]
No resource problem yet. I'll close this one.

I am using carbon-c-relay in a 2-node cluster. All metrics replicated between them on 3.2tb fusionio. I hope this cluster will be able to handle 40-45k datapoints/sec input. The python daemons have already proven incapable.

**Comment by grobian** [comment]
![render-2](https://cloud.githubusercontent.com/assets/667105/9521016/4fa06e10-4ccc-11e5-8f84-bb78abfea06f.png)
we do up to 45K/sec on some of our clusters (SSD-based)
